JDP211201-14 cart entity
piotr-grosicki/project-jdp-2112-01 pull request #12
Opened 2022-01-05 09:17 UTC by LukasM1987

2022-01-05 13:21 UTC, piotr-grosicki requested changes

2022-01-05 13:21 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/repository/CartRepository.java
> +    List<Cart> findById(long id);
dlaczego findById zwraca liste?

2022-01-05 13:21 UTC, piotr-grosicki requested changes
konflikty do poprawienia: np https://www.jetbrains.com/help/idea/resolving-conflicts.html

2022-01-06 08:03 UTC, LukasM1987 commented
kurcze dziwne, bo przed wysłaniem mi się zbudował gradle.

2022-01-07 07:54 UTC, piotr-grosicki approved these changes

2022-01-07 07:54 UTC, merged