Jdp211201-20
piotr-grosicki/project-jdp-2112-01 pull request #16
Opened 2022-01-05 17:24 UTC by SebaaK

2022-01-06 11:48 UTC, MartaKruk commented on src/main/java/com/kodilla/ecommercee/CartController.java
> -    }
Wygląda jakby część plików była tu usunięta lub wyczyszczona i nie zastąpiona niczym nowym. Z czego to wynika?

2022-01-06 12:31 UTC, MartaKruk requested changes

2022-01-07 18:44 UTC, SebaaK commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +}
Ogólnie Piotr mówił o tym, że jeśli jest dobry Persist nie trzeba robić testów, ale okej :P

2022-01-07 18:44 UTC, SebaaK commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +}
Ogólnie Piotr mówił o tym, że jeśli jest dobry Persist nie trzeba robić testów, ale okej :P

2022-01-07 19:14 UTC, MartaKruk commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +}
Hmh, to może tego nie wyłapałam. Ja pamiętam, że mówił że trzeba zrobić zgodnie z opisem zadania w Jirze, a tam jest: "Jeśli encja posiada relacje, zastanów się, co powinno się stać z powiązanymi obiektami. Sprawdź to za pomocą testów." Dlatego sama jak robiłam to też relacje testowałam.

2022-01-08 12:57 UTC, jasokolowska commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +}
też bym dodala sprawdzenie pozostałych encji, bo jak sie w praktyce okazuje, to jest z tym problem ;) 
czyli lepiej byłoby sprawdzic czy się usunęły zamówienia i carta, bo tak praktycznie patrzac jak usuwamy User'a to po co ma nam zostac jego koszyk lub zamówienia....

2022-01-08 14:16 UTC, closed without merging